services:
  - type: web
    name: debatex-final-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        fromDatabase:
          name: debatex-mongodb
          property: connectionString
      - key: DB_NAME
        value: debatex
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://nipungarg1608.github.io"
    autoDeploy: true

databases:
  - name: debatex-mongodb
    type: mongodb
    region: oregon
    plan: free